French translations
QuiltMC/enigma pull request #115
Opened 2023-06-13 13:56 UTC by Mysterious-Dev

I'm back ^^.

This PR add french translations for all new keys add after my first PR.

It need more work, so I open this on on draft

2023-06-14 09:20 UTC, Mysterious-Dev commented
@ix0rai Ready for review ^^ !

2023-06-14 15:13 UTC, ix0rai requested changes
Les 4 pour `package_rename` sont tous à conjugés l'infinitif, pourquoi? Tu peut voir dans l'anglais qu'ils indique une action qui est mi-exécution.

2023-06-16 12:35 UTC, Mysterious-Dev commented
@ix0rai I applied your requests ^^

2023-06-16 12:35 UTC, Mysterious-Dev commented
It's weird, why my commit do not appear on the timeline (client bug maybe) ?
![image](https://github.com/QuiltMC/enigma/assets/40738104/1ced1673-8525-4694-988c-d03d16ea9bbd)

2023-06-16 12:37 UTC, ix0rai approved these changes

2023-06-16 22:36 UTC, merged